# Generated by Django 4.2.6 on 2023-10-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_end_alter_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
