# Generated by Django 4.2.6 on 2023-10-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_end_alter_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_tasks', to='tasks.task'),
        ),
    ]
